### ISSUE TITLE
AntiPopup is causing players to be kicked when chat messages are cancelled by other plugins when using behind a proxy.

### ISSUE THREAD

**Issue by mibby** [KaspianDev/AntiPopup#10]
See for more info: https://github.com/PaperMC/Paper/issues/8275#issuecomment-1213611642

**Comment by KaspianDev** [comment]
I'll push a patch today hopefully fixing it.

**Comment by KaspianDev** [comment]
@mibby please also send me your plugin list

**Comment by KaspianDev** [comment]
https://github.com/KaspianDev/AntiPopup/actions/runs/2851827834
let me know if it fixes the issue

**Comment by mibby** [comment]
So far so good. Fingers crossed.

**Comment by KaspianDev** [comment]
Okay, if it pops up reopen the issue.
