### ISSUE TITLE
[BUG] Netty Packet crash to server w/o plugin

### ISSUE THREAD

**Issue by bradcarnage** [KaspianDev/AntiPopup#100]
### Describe the bug

I get a "unknown packet serverbound/minecraft:chat_session_update" error from the client, when connecting to a velocity instance with the plugin, where the backend server does not have the plugin. 

It would be useful to not require the plugin on the backend server for performance/simplicity reasons. additionally, it might be impossible to install the plugin on the backend server is not a flavor of bukkit/spigot/paper/etc. (say for example vanilla, fabric, or forge)

### To Reproduce

Install the plugin on a velocity proxy instance, but not on the backend server.

### Expected behavior

Custom packets to not be sent through the proxy to the client, causing a connection termination.

### Operating System

Linux Mint

### Server Software

Velocity 3.3.0-SNAPSHOT (git-00ed2284-b415), paper-1.21.1-33

### Server Version

Not Listed

### Proxy Type

Velocity

### Plugin List

```bash
> velocity plugins
[12:05:45 INFO]: Plugins: antipopup, pistonqueue, skinsrestorer, viaversion, viabackwards

> plugins
[12:05:39 INFO]: Server Plugins (4):
[12:05:39 INFO]: Bukkit Plugins:
[12:05:39 INFO]:  - AntiPopup, PistonQueueBukkit, ViaBackwards, ViaVersion

> plugins
[12:06:15 INFO]: Server Plugins (4):
[12:06:15 INFO]: Bukkit Plugins:
[12:06:15 INFO]:  - AntiPopup, LuckPerms, ViaBackwards, ViaVersion
```

### Server logs

https://gist.github.com/bradcarnage/9d94ac5899c3676efe43db0923b34e75

**Comment by KaspianDev** [comment]
AntiPopup only blocks the popup on velocity. It needs to be installed on all backend servers as well.
You shouldn't worry about performance, packetevents handles packed asynchronously.
