### ISSUE TITLE
[BUG] Large memory usage due to PacketEvents dependency

### ISSUE THREAD

**Issue by BitByLogics** [KaspianDev/AntiPopup#101]
### Describe the bug

While reviewing some heap reports from spark I noticed that AntiPopup was 13th in order of memory used. I assume this is something that PacketEvents is doing as AntiPopup doesn't use the "WrappedBlockState" object.

### To Reproduce

1. Boot up a server with AntiPopup (with spark)
2. Take heap summary report using /spark heapsummary
3. Large memory usage shows

![image](https://github.com/user-attachments/assets/95b3ad29-3e90-4751-985d-919a604c26c8)

### Operating System

Windows

### Server Software

Purpur 1.21.1-2286-366af80

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
AntiPopup, APIByLogic, Citizens, DecentHolograms, DisplayEntityEditor, Essentials, EssentialsSpawn, FastAsyncWorldEdit, LogicUtils, LuckPerms, Multiverse-Core, PlaceholderAPI, ProtocolLib, TAB, Tebex, TidalCore, Vault, VoidGen, Votifier, WorldGuard
```

### Server logs

N/A

**Comment by KaspianDev** [comment]
https://github.com/retrooper/packetevents/issues/965
https://github.com/retrooper/packetevents/issues/964

Will update PE once resolved
