### ISSUE TITLE
[BUG] Does not let player join on 1.21.3 Spigot

### ISSUE THREAD

**Issue by mrjasonn** [KaspianDev/AntiPopup#103]
### Describe the bug

It says disconnected null due to invalid packet. This is probably due to the plugin not updated for 1.21.3

### To Reproduce

1. Open a Spigot 1.21.3 server with AntiPopup
2. Try to join it

### Operating System

Windows

### Server Software

4353-Spigot-5eb8a94-18b8ae1

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
Not needed
```

### Server logs

Not needed

**Comment by Onako2** [comment]
Is currently in progress

**Comment by BySwiizen** [comment]
https://github.com/retrooper/packetevents/releases/tag/v2.6.0

**Comment by quiquelhappy** [comment]
![sussa](https://github.com/user-attachments/assets/367254ae-cd52-4df5-8ecb-c60b00ea6fe7)
