### ISSUE TITLE
[Question] How can I verify that it works

### ISSUE THREAD

**Issue by TheRobLP** [KaspianDev/AntiPopup#104]
Hey there. I am using AntiPopup on my 1.20.6 Paper server. /plugins says it is enabled, but I am uncertain if it really works. The reason is, because I just installed the Wurst mod for Fabric because I want to test my Anticheat. and the mod warned me that chat reporting is still enabled. Now I don't know if Wurst is just confused because of how the plugin does stuff, or if it really is not working. Is there any way to verify if the plugin works correctly? Thanks in advance.

Sincerly
TheRobLP

**Comment by KaspianDev** [comment]
Game client is tricked into thinking chat reporting is enabled while it's off. To verify get another player (test on vanilla) and tell him to send any message, then in your client (also vanilla) try reporting that message in the social menu (press P).
