### ISSUE TITLE
[BUG] kicks players on 1.21.4

### ISSUE THREAD

**Issue by quiquelhappy** [KaspianDev/AntiPopup#106]
### Describe the bug

due to packetevents not being up to date

### To Reproduce

use spigot 1.21.4, place any block

### Operating System

-

### Server Software

spigot --rev 1.21.4

### Server Version

Not Listed

### Proxy Type

Bungeecord

### Plugin List

```bash
-
```

### Server logs

-

**Comment by Stoupy51** [comment]
Having same issue!
