### ISSUE TITLE
Ability to set content of popup instead

### ISSUE THREAD

**Issue by PikaMug** [KaspianDev/AntiPopup#2]
Seems like this might be possible? https://github.com/retrooper/packetevents/blob/8aeef01bd4223c52322a44d3ceb44bcec5a3a388/api/src/main/java/com/github/retrooper/packetevents/protocol/chat/message/ChatMessage.java#L41

**Comment by KaspianDev** [comment]
> Seems like this might be possible? https://github.com/retrooper/packetevents/blob/8aeef01bd4223c52322a44d3ceb44bcec5a3a388/api/src/main/java/com/github/retrooper/packetevents/protocol/chat/message/ChatMessage.java#L41

That one is for messages, not popup tho?

**Comment by PikaMug** [comment]
That takes a boolean. I'm talking about changing the text.

**Comment by KaspianDev** [comment]
> That takes a boolean. I'm talking about changing the text.

I'll tinker with it tomorrow, if you find something earlier feel free to PR.

**Comment by SamB440** [comment]
Unfortunately, I'm pretty certain the text is clientside.

The client just displays the insecure popup to itself if that boolean is false.

ChatMessage is an unrelated class, that's to do with actually sending a chat message.

**Comment by PikaMug** [comment]
Haven't seen anything concrete about the text being client-side, but I clearly misinterpreted that class. Thank you both.
