### ISSUE TITLE
Players getting kicked with "Disconnected" error after 5 minutes

### ISSUE THREAD

**Issue by VacBanYT** [KaspianDev/AntiPopup#21]
After updating to Antipopup 5.0, my whole server started to get kicked of server with no errors in console.
Everyone had "Disconnected" as the reason for the kick.
The server was doing fine without any lags, stable 20 TPS and everyone was getting kicked every 2-5 minutes.
After changing back to v. 4.5 everyone is fixed.
It looked like a Time Out error, but the players' connection had no problem.

Version: 1.19.2 Paper
AntiPopUp: 5.0

**Comment by KaspianDev** [comment]
Please use 5.1

**Comment by VacBanYT** [comment]
The same problem on version 5.1 after around 5 minutes 50% of players are getting disconnected with the error "Disconnected" and TimeOut on the player side.

**Comment by KaspianDev** [comment]
I need the plugin list and full server log.
