### ISSUE TITLE
Disconnect from server after sending message.

### ISSUE THREAD

**Issue by Lemonray114** [KaspianDev/AntiPopup#22]
Version: 1.19.2 
AntiPopup: 5.1

Hi, i still have a problem that someone typing in the chat and the players in whole server will disconnect from it .
![image](https://user-images.githubusercontent.com/91263844/206861948-39b57161-bae1-4218-8d7f-157571375828.png)

**Comment by KaspianDev** [comment]
I need your plugin list and server logs.

**Comment by KaspianDev** [comment]
In meanwhile please try [this build](https://github.com/KaspianDev/AntiPopup/actions/runs/3660903562).

**Comment by KaspianDev** [comment]
This is most likely fixed in newest versions. Closing as completed as I've seen no reports of that for a long time.
