### ISSUE TITLE
[BUG] When restarting server

### ISSUE THREAD

**Issue by PaladinFallen** [KaspianDev/AntiPopup#32]
**Describe the bug**
Restarting server, we get a error

**To Reproduce**
1. Restart server
2. Look at Log

**Expected behavior**
....No error to happen?

**Screenshots**
N/A

**Server information:**
 - Operating System (for example Rocky 9): Debian 11
 - Server Software (for example Spigot): Paper
 - Server Version (for example 1.19.2): 1.19.3 version 368
 - Plugin list: 

Alchema-1.3.0-SNAPSHOT
AntiPopup-5.2
AntiVillagerLag-2.1.4
AppleTreeReloaded-1.3.1
AutoComposter-3.4.0
AutoCraft-2.3.0
AutoShulker-3.5.0
AutoTotem-1.1.0
BedrockMiner-v2.0.0
beenfo-1.19.1-fabric0.58.5-1.3.3-spigot
BetterLogStrip-1.1.1
BetterPortals-0.12.1
BetterStairs
BetterTridents-2.2.2
BKCommonLib-1.19.3-v2-SNAPSHOT-1452
BlockLocker
BreakingSlab-1.0.1
ChestShop
ChestShopNotifier
ChorusDrops-1.4
Chunky-1.3.52
cleanping-1.1
CleanroomGenerator-1.2.1
CMILib1.2.4.1
ComposterPlus
CrashAPI
custom-discs-2.2.3
CytologicHorses-1.4.0-public
DeathGhosts-1.0.0
DecaliumTweaks-1.0
Dimensions
DispensablePlants_v1.0.0
DispenserRobot-1.3.5
DoorsReloaded-1.3.1
DualWield-3.0
Dynmap-3.5-SNAPSHOT-spigot
DynmapBannerMarkers-1.2.0
EasyBackupCore
easybackup-plugin-3.3.7
EnchantmentSolution
EnchantPlus-1.3.5
EnchantsSquared
EnhancedEnchants
EssentialsX-2.20.0-dev+37-b7a4bea
EssentialsXChat-2.20.0-dev+37-b7a4bea
EssentialsXDiscord-2.20.0-dev+37-b7a4bea
EssentialsXGeoIP-2.20.0-dev+37-b7a4bea
farmingupgrade-1.3.6
FInvsee
FishingExhaust-1.0
FixedPortals-1.0.0
Harbor-1.6.3
HarvestEXP+Build+4a
HideNametag
Hitmarkers+Build+16b
InvSort_2.0.1
ItemDisenchanter
ItemEdit-3.0.7
ItemJoin-5.2.6-SNAPSHOT-b861
Jobs5.1.1.1
LagAssist-2.29.1
LanBroadcaster
LargeRaids
LavaFurnace-1.0-SNAPSHOT
LevelTools-1.3.2
LightAPI-Bukkit-5.3.0
LightCleaner-1.19.2-v1-SNAPSHOT-145
LiteEco-1.1.8-SNAPSHOT
MapModCompanion
mcMMO
MendingEnchant-1.6.1
MilkSplash-1.2.1
Minepacks-2.4.11-Release
MineTweaks-1.8.2
Multiverse-Core-4.3.2-SNAPSHOT
Multiverse-Inventories-4.2.4-SNAPSHOT
Multiverse-Portals-4.2.2-SNAPSHOT
MyPet-3.12-SNAPSHOT-B1732
NDailyRewards-1.5.7
OfflineGrowthPro-1.6.9
PCGF_PluginLib-1.0.39-SNAPSHOT
Petting-1.3
PickupArrows
ProtocolLib
PwnChickenLay
RandomThings-1.2
RealisticSeasons-10.2.1
RotationWrench-1.7.1
SandDupe
Shopkeepers-2.16.3
ShulkerRespawner-1.13_1.0.10
ShulkerRespawnerLib119-1.0.0
SilkSpawners
SilkSpawnersEcoAddon
SlimeInABukkit-1.2
SmartMoving-1.0.1-all
spark-1.10.17-bukkit
StackResize-1.3.0
TabLocation-1.5.0
Teaks.Tweaks.-.1.8.0-beta
Tether-2.5.0
TrainCarts-1.19.3-v2-SNAPSHOT-1286
UltimateAutoRestart+ Build 52c
UnlimitedLava
Vault
VeinMiner-Bukkit-2.0.0
VillagerInfo-2.5
voicechat-bukkit-1.19.3-2.3.24
voicechat-discord-paper-1.4.0
VoidTotem
worldedit-bukkit-7.2.14-SNAPSHOT-dist
worldguard-bukkit-7.0.8-SNAPSHOT-dist
xaero-map-spigot-1.0.0
YamipaPlugin-1.2.7

**Latest log file**
https://gist.github.com/PaladinFallen/f93fb319fbeb04f56691563dee3a8c35

**Additional context**
N/A

**Comment by KaspianDev** [comment]
This is pretty rare and harmless, perhaps try reporting that to packetevents.

**Comment by KaspianDev** [comment]
Sloving as It's most likely not related to AntiPopup.
