### ISSUE TITLE
[BUG] Everyone gets kicked when sending a chat message

### ISSUE THREAD

**Issue by TheBlackEntity** [KaspianDev/AntiPopup#33]
**Describe the bug**
As soon as anyone tries to send a chat message, everyone gets kicked from the server.

**To Reproduce**
1. Try to send a chat message

**Expected behavior**
Noone gets kicked and message is sent.

**Server information:**
 - Debian 11
 - Petal Spigot (with BungeeCord version: git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:e717676:1672)
 - 1.19.2
 - Plugin list:
    - AdvancedReplay
    - AntiCheatReplay
    - BKCommonLib
    - ChestSort
    - DecentHolograms
    - EconomyShopGUI
    - FastAsyncWorldEdit (WorldEdit)
    - GriefPrevention
    - Iris
    - LeavesDecay
    - LuckPerms
    - Multiverse-Core
    - PlaceholderAPI
    - PlugManX (PlugMan)
    - PrefixSystem
    - Prism
    - ProtocolLib
    - QuickShop
    - RHLeafDecay
    - ServersNPC
    - ServerSystem
    - ShopSorter
    - SkBee
    - SkQuery
    - Skript
    - spark
    - TramaniaClasses
    - Vault
    - ViaBackwards (Only allowing 1.17 - 1.19.3 though, it's also *not* installed on the proxy)
    - ViaVersion
    - Vulcan
    - WorldEditSUI
    - WorldGuard

**Latest log file**
Not needed, there are no exceptions.
I triple and quadruple checked, it's not worth the censoring just to prove there are none

**Comment by KaspianDev** [comment]
I dont see antipopup on the list

**Comment by KaspianDev** [comment]
Also, I cannot work without logs, if you are worried you can either send them in private or/and just include relevant parts.
Unless there absolutely no relevant logs tho I doubt that, I don't even know what message players get on kick.

**Comment by TheBlackEntity** [comment]
> I dont see antipopup on the list

Yes, because this is the list after I removed AntiPopup because of this issue.

> Also, I cannot work without logs, if you are worried you can either send them in private or/and just include relevant parts.
> Unless there absolutely no relevant logs tho I doubt that, I don't even know what message players get on kick.

Here's a log from a copy of the server:
https://pastebin.com/HmXy6qbT

I checked the proxy log this time:
16:38:21 [WARNUNG] [TestAccount666] <-> DownstreamBridge <-> [TestFreebuild] - could not decode packet! java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 32768))

**Comment by KaspianDev** [comment]
send me your config and server.properties (be sure not to leak anything)

**Comment by TheBlackEntity** [comment]
Config:
https://pastebin.com/q964kphx

Server.properties:
https://pastebin.com/YknQmH91

**Comment by KaspianDev** [comment]
@TheBlackEntity please confirm if it's fixed in spigot release.
