### ISSUE TITLE
[BUG] Plugin didn't shutdown correctly

### ISSUE THREAD

**Issue by PalmTamino** [KaspianDev/AntiPopup#34]
**Describe the bug**
I just shutdown the server and this little error came up in console, it's not a big thing ig but worth reporting.

**To Reproduce**
1: Shutdown server?

**Expected behavior**
No error

**Server information:**
 - Operating System (for example Rocky 9): Ubuntu
 - Server Software (for example Spigot): Purpur 1.19.3 (1886)
 - Server Version 1.19.3
 - Plugin list:
AdvancedArmorStands, AntiPopup, Citizens, CommandForward, ConsoleFilter, CoreProtect, DecentHolograms, EndurionCore, EndurionLobbySystem, FastAsyncWorldEdit, GSit, LuckPerms, PlaceholderAPI, Plan, ProtocolLib, ServerUtils, TAB-Bridge, Triton, UltraCustomizer, Vault, ViaBackwards, ViaVersion, ajQueue, floodgate and spark
**Stacktrace**
https://paste.gg/p/anonymous/7f3c43a33ade408a918452dcd48c67e2
**Additional context**
Plugin loaded without any errors.

**Comment by KaspianDev** [comment]
Not harmful, it just happens sometimes you can ignore it.

**Comment by PalmTamino** [comment]
Why don’t you just fix it? Of course its not a problem, but please do it properly and shutdown you plugin correctly.

**Comment by PalmTamino** [comment]
Why don’t you just fix it? Of course its not a problem, but please do it properly and shutdown you plugin correctly.

**Comment by KaspianDev** [comment]
> Why don’t you just fix it? Of course its not a problem, but please do it properly and shutdown you plugin correctly.

If you are able to reproduce the issue all the time I can suppress the warning. Message me on discord.
