### ISSUE TITLE
[BUG] PacketEvents caught an unhandled exception while calling your listener

### ISSUE THREAD

**Issue by paul-eff** [KaspianDev/AntiPopup#35]
**Describe the bug**
Error randomly popped up while server was idling. No players online for 10-15 hours, no updates/restarts/etc.

**Server information:**
 - Operating System: Ubuntu 20.04
 - Server Software: Paper
 - Server Version: 371
 - Plugin list: AntiPopup (v5.2), DriveBackupV2, dynmap, WorldEdit

**Latest log file**
GitHub Gist [here](https://gist.github.com/paul-eff/7d9b31052b7141cebc7e1bab9493eed0)

**Comment by KaspianDev** [comment]
Please report this to packetevents
