### ISSUE TITLE
Intermittent EncoderException

### ISSUE THREAD

**Issue by SlimeDog** [KaspianDev/AntiPopup#37]
### Describe the bug

**Intermittent** `EncoderException`. It occurs intermittently on server restart. It also occurs intermittently after server restart.

### To Reproduce

- Start server
- Read log

### Expected behavior

(Relatively) clean start-up

### Operating System

CentOS Linux release 7.9.2009 (Core)

### Server Software

Spigot 1.19.3-3647 or Paper 1.19.3-386

### Server Version

1.19.3

### Proxy Type

None

### Plugin List

```
Lots. See attached log file.
```

### Server logs

REMOVED
REMOVED

**Comment by KaspianDev** [comment]
Does it show up when my plugin isn't present?

**Comment by KaspianDev** [comment]
Please open an issue on PacketEvents

**Comment by SlimeDog** [comment]
Done.

**Comment by SlimeDog** [comment]
There have been quite a few commits to https://github.com/retrooper/packetevents/commits/2.0 (the branch I believe AntiPopup is using) since the version used in AntiPopup 5.3. In fact, the number of commits posted daily is truly startling. No idea if any of them fix this particular issue. The [linked issue](https://github.com/retrooper/packetevents/issues/533) has received no response, to date.

**Comment by SlimeDog** [comment]
Did you test it? I got the same issue, on the first try. He still has not responded to the [linked issue](https://github.com/retrooper/packetevents/issues/533).

**Comment by SlimeDog** [comment]
More important, I don't see any test modules in the PacketEvents source (perhaps I missed them, but I don't think so). It seems unwise to rely on completely untested code in your own plugin, especially given the code-du-jour updates. Perhaps you should consider extracting the relevant code (how many protocol interfaces does AntiPopup use?) since it's published under a GPL3 license, so that you can test your own usage without reliance on bleeding edge interfaces.

**Comment by KaspianDev** [comment]
> Did you test it? I got the same issue, on the first try. Retrooper still has not responded to the [linked issue](https://github.com/retrooper/packetevents/issues/533).

yeah sorry i couldnt test that one and it causes issues for me too, im waiting for their response

**Comment by RainbowTea** [comment]
I'm having the same issue i think?
https://hastebin.com/share/fukumodeta.markdown

Adding to it and not opening a new issue. Hope that's okay..

**Comment by KaspianDev** [comment]
> I'm having the same issue i think? https://hastebin.com/share/fukumodeta.markdown
> 
> Adding to it and not opening a new issue. Hope that's okay..

message me on discord/matrix

**Comment by SlimeDog** [comment]
Per https://github.com/retrooper/packetevents/issues/533#issuecomment-1428423653, this issue has been resolved.

**Comment by KaspianDev** [comment]
ive made a test release [here](https://github.com/KaspianDev/AntiPopup/releases/tag/fc52664). note it is untested since i cant reproduce the issue.

**Comment by SlimeDog** [comment]
RC2 running on Paper and Spigot for nearly two hours, including a few restarts, without error.

**Comment by KaspianDev** [comment]
okay lets give it time till im back from school tomorrow
@RainbowTea maybe you also wanna test?

**Comment by arturek1666** [comment]
Oh I have that issue as well will get the test release as well and see how it goes :)

**Comment by KaspianDev** [comment]
sweet

**Comment by RainbowTea** [comment]
> okay lets give it time till im back from school tomorrow @RainbowTea maybe you also wanna test?

Booted up with no errors so far!  Thank you :)
