### ISSUE TITLE
1.19 server antipopup not work

### ISSUE THREAD

**Issue by tygh78071388** [KaspianDev/AntiPopup#4]
[Netty Server IO #1/WARN]: [AntiPopup] Loaded class com.viaversion.viaversion.api.Via from ViaVersion v4.4.1 which is not a depend or softdepend of this plugin.

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

**Comment by KaspianDev** [comment]
> [Netty Server IO #1/WARN]: [AntiPopup] Loaded class com.viaversion.viaversion.api.Via from ViaVersion v4.4.1 which is not a depend or softdepend of this plugin.
> 
> This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

Antipopup isn't needed on 1.19 server as 1.19 doesn't have reporting, versions 1.19.1+ have

**Comment by KaspianDev** [comment]
If you get any errors send them here

**Comment by tygh78071388** [comment]
> If you get any errors send them here

server is 1.19, use ViaVersion plugin 
So 1.19.1 players can join and see popup

I don't know if there is a solution
THX!

**Comment by KaspianDev** [comment]
> > If you get any errors send them here
> 
> server is 1.19, use ViaVersion plugin So 1.19.1 players can join and see popup
> 
> I don't know if there is a solution THX!

Please try out jar in this workflow: https://github.com/KaspianDev/AntiPopup/actions/runs/2776590754
It should make sure only 1.19.1 or newer players are affected.

**Comment by tygh78071388** [comment]
> > > If you get any errors send them here
> > 
> > 
> > server is 1.19, use ViaVersion plugin So 1.19.1 players can join and see popup
> > I don't know if there is a solution THX!
> 
> Please try out jar in this workflow: https://github.com/KaspianDev/AntiPopup/actions/runs/2776590754 It should make sure only 1.19.1 or newer players are affected.

FIX!  THX!!!

**Comment by KaspianDev** [comment]
> > > > If you get any errors send them here
> > > 
> > > 
> > > server is 1.19, use ViaVersion plugin So 1.19.1 players can join and see popup
> > > I don't know if there is a solution THX!
> > 
> > 
> > Please try out jar in this workflow: https://github.com/KaspianDev/AntiPopup/actions/runs/2776590754 It should make sure only 1.19.1 or newer players are affected.
> 
> FIX! THX!!!

Great

**Comment by tygh78071388** [comment]
> > > > > If you get any errors send them here
> > > > 
> > > > 
> > > > server is 1.19, use ViaVersion plugin So 1.19.1 players can join and see popup
> > > > I don't know if there is a solution THX!
> > > 
> > > 
> > > Please try out jar in this workflow: https://github.com/KaspianDev/AntiPopup/actions/runs/2776590754 It should make sure only 1.19.1 or newer players are affected.
> > 
> > 
> > FIX! THX!!!
> 
> Great, for now use this jar, new version will be on spigot soon

wait...  umm I just used the 1.19 client  sorry

**Comment by tygh78071388** [comment]
> > > > > > If you get any errors send them here
> > > > > 
> > > > > 
> > > > > server is 1.19, use ViaVersion plugin So 1.19.1 players can join and see popup
> > > > > I don't know if there is a solution THX!
> > > > 
> > > > 
> > > > Please try out jar in this workflow: https://github.com/KaspianDev/AntiPopup/actions/runs/2776590754 It should make sure only 1.19.1 or newer players are affected.
> > > 
> > > 
> > > FIX! THX!!!
> > 
> > 
> > Great, for now use this jar, new version will be on spigot soon
> 
> wait... umm I just used the 1.19 client sorry

[AntiPopup] Enabling AntiPopup v2.3
[16:27:05] [Server thread/INFO]: [AntiPopup] Initiated PacketEvents
[16:27:05] [Server thread/INFO]: [AntiPopup] Config enabled.
[16:27:05] [Server thread/INFO]: [AntiPopup] true

[16:27:40] [Netty Server IO #1/WARN]: [AntiPopup] Loaded class com.viaversion.viaversion.api.Via from ViaVersion v4.4.1 which is not a depend or softdepend of this plugin.
[16:27:40] [User Authenticator #1/INFO]: UUID of player tygh89071388 is 3c4767a1-0421-4614-bedc-501e86943621

**Comment by KaspianDev** [comment]
> > > > > > > If you get any errors send them here
> > > > > > 
> > > > > > 
> > > > > > server is 1.19, use ViaVersion plugin So 1.19.1 players can join and see popup
> > > > > > I don't know if there is a solution THX!
> > > > > 
> > > > > 
> > > > > Please try out jar in this workflow: https://github.com/KaspianDev/AntiPopup/actions/runs/2776590754 It should make sure only 1.19.1 or newer players are affected.
> > > > 
> > > > 
> > > > FIX! THX!!!
> > > 
> > > 
> > > Great, for now use this jar, new version will be on spigot soon
> > 
> > 
> > wait... umm I just used the 1.19 client sorry
> 
> [AntiPopup] Enabling AntiPopup v2.3 [16:27:05] [Server thread/INFO]: [AntiPopup] Initiated PacketEvents [16:27:05] [Server thread/INFO]: [AntiPopup] Config enabled. [16:27:05] [Server thread/INFO]: [AntiPopup] true
> 
> [16:27:40] [Netty Server IO #1/WARN]: [AntiPopup] Loaded class com.viaversion.viaversion.api.Via from ViaVersion v4.4.1 which is not a depend or softdepend of this plugin. [16:27:40] [User Authenticator #1/INFO]: UUID of player tygh89071388 is 3c4767a1-0421-4614-bedc-501e86943621

do you get kicked or something?

**Comment by tygh78071388** [comment]
> > > > > > > > If you get any errors send them here
> > > > > > > 
> > > > > > > 
> > > > > > > server is 1.19, use ViaVersion plugin So 1.19.1 players can join and see popup
> > > > > > > I don't know if there is a solution THX!
> > > > > > 
> > > > > > 
> > > > > > Please try out jar in this workflow: https://github.com/KaspianDev/AntiPopup/actions/runs/2776590754 It should make sure only 1.19.1 or newer players are affected.
> > > > > 
> > > > > 
> > > > > FIX! THX!!!
> > > > 
> > > > 
> > > > Great, for now use this jar, new version will be on spigot soon
> > > 
> > > 
> > > wait... umm I just used the 1.19 client sorry
> > 
> > 
> > [AntiPopup] Enabling AntiPopup v2.3 [16:27:05] [Server thread/INFO]: [AntiPopup] Initiated PacketEvents [16:27:05] [Server thread/INFO]: [AntiPopup] Config enabled. [16:27:05] [Server thread/INFO]: [AntiPopup] true
> > [16:27:40] [Netty Server IO #1/WARN]: [AntiPopup] Loaded class com.viaversion.viaversion.api.Via from ViaVersion v4.4.1 which is not a depend or softdepend of this plugin. [16:27:40] [User Authenticator #1/INFO]: UUID of player tygh89071388 is 3c4767a1-0421-4614-bedc-501e86943621
> 
> do you get kicked or something?

join normally

**Comment by KaspianDev** [comment]
`[16:27:40] [Netty Server IO https://github.com/KaspianDev/AntiPopup/pull/1/WARN]: [AntiPopup] Loaded class com.viaversion.viaversion.api.Via from ViaVersion v4.4.1 which is not a depend or softdepend of this plugin.`}
If you mean this line, it's not an error you can safely ignore it

**Comment by tygh78071388** [comment]
ProtocolLib
version: 5.0.0-SNAPSHOT-b586

**Comment by KaspianDev** [comment]
Got it, I will try to fix it

**Comment by tygh78071388** [comment]
> Got it, I will try to fix it

Thanks for your assistance.
Can I make a one-time donation?

**Comment by KaspianDev** [comment]
> > Got it, I will try to fix it
> 
> Thanks for your assistance. Can I make a one-time donation?

Sure if you want, my Liberapay is on resource page on spigot

**Comment by KaspianDev** [comment]
@tygh78071388 message me on discord Kaspian#0870, I will send you a fixed jar. I cannot send jars here sadly.

**Comment by KaspianDev** [comment]
Resolved in latest version
