### ISSUE TITLE
Will this work?

### ISSUE THREAD

**Issue by GAMINGCHATS** [KaspianDev/AntiPopup#41]
I've made a Reddit post about a problem I'm having _without_ installing the plugin. _Yet_.
[Reddit Post](https://www.reddit.com/r/admincraft/comments/11ejav4/psa_chat_message_validation_failure/?utm_source=share&utm_medium=web2x&context=3)

**Comment by KaspianDev** [comment]
not sure what you mean, please explain

**Comment by KaspianDev** [comment]
stale. closing.
