### ISSUE TITLE
Support 1.19.4?

### ISSUE THREAD

**Issue by BySwiizen** [KaspianDev/AntiPopup#42]
Hi, the plugin will soon be updated for 1.19.4?

**Comment by KaspianDev** [comment]
Yes all code is waiting to be pushed. There is one error right now related to dependency so I'm waiting for a fix.

**Comment by CloudeLecaw** [comment]
glad to here the plugin will get 1.19.4 support

**Comment by BySwiizen** [comment]
> Oui, tout le code attend d'être poussé. Il y a actuellement une erreur liée à la dépendance, j'attends donc un correctif.

Are you also waiting for a ProtocolLib fix?

**Comment by BySwiizen** [comment]
> Yes all code is waiting to be pushed. There is one error right now related to dependency so I'm waiting for a fix.

Are you also waiting for a ProtocolLib fix?

**Comment by KaspianDev** [comment]
> > Yes all code is waiting to be pushed. There is one error right now related to dependency so I'm waiting for a fix.
> 
> Are you also waiting for a ProtocolLib fix?

antipopup is using packetevents

**Comment by KaspianDev** [comment]
keep open until released

**Comment by BySwiizen** [comment]
> keep open until released

I'll let you know when a fix is available!

**Comment by BySwiizen** [comment]
@KaspianDev, ProtocolLib has been updated for 1.19.4!

**Comment by KaspianDev** [comment]
> @KaspianDev, ProtocolLib has been updated for 1.19.4!

My plugin is not using protocollib
https://github.com/retrooper/packetevents/issues/562

**Comment by BySwiizen** [comment]
> > @KaspianDev, ProtocolLib has been updated for 1.19.4!
> 
> My plugin is not using protocollib [retrooper/packetevents#562](https://github.com/retrooper/packetevents/issues/562)

The developer is currently working on it

**Comment by MrCrazyAndy** [comment]
Is there any update on this? if i install the version that it gives me though the plugin list on my server console, it gives me an internal exception, but need the plugin to protect members against random reports.

**Comment by KaspianDev** [comment]
> Is there any update on this? if i install the version that it gives me though the plugin list on my server console, it gives me an internal exception, but need the plugin to protect members against random reports.

if you dont mind the warnings check out 5.5 branch.

**Comment by MrCrazyAndy** [comment]
> > Is there any update on this? if i install the version that it gives me though the plugin list on my server console, it gives me an internal exception, but need the plugin to protect members against random reports.
> 
> if you dont mind the warnings check out 5.5 branch.

May i ask where i go to get this?

**Comment by KaspianDev** [comment]
https://github.com/KaspianDev/AntiPopup/tree/5.5

**Comment by CloudeLecaw** [comment]
> https://github.com/KaspianDev/AntiPopup/tree/5.5
> 
> you build it like any other gradle project. `./gradlew build`

i aspect he cant compile itself and searched for a ready to download ;)

**Comment by BySwiizen** [comment]
> > https://github.com/KaspianDev/AntiPopup/tree/5.5
> > you build it like any other gradle project. `./gradlew build`
> 
> i aspect he cant compile itself and searched for a ready to download ;)

I have the same problem.

**Comment by KaspianDev** [comment]
@BySwiizen @MrCrazyAndy @CloudeLecaw 

Here's the latest release: https://github.com/KaspianDev/AntiPopup/releases/tag/764c2ad
Let me know if it works with no issues and confirm by either commenting or closing the issue.

**Comment by CloudeLecaw** [comment]
> @BySwiizen @MrCrazyAndy @CloudeLecaw
> 
> Here's the latest release: https://github.com/KaspianDev/AntiPopup/releases/tag/764c2ad Let me know if it works with no issues and confirm by either commenting or closing the issue.

I agree with Bywiizen. it works like a charm in paper 1.19.4.
i specified nothing... so what do you mean?

```
this is my current config.
config-version: '28'

# Should we collect anonymous data about your server?
# false by default.
bstats: false

# Should we remove [Not Secure] from /say?
# There is a very small chance of catching something
# that should not be caught. If that happens report the
# incident to Github issues of AntiPopup.
filter-not-secure: true

# Should we prevent messages from being reported?
# Leave as true unless you have a different plugin stripping those.
strip-signature: true

# We dont need that packet if
# we dont sign messages.
dont-send-header: true

# Should setup be ran on first start?
# Useful for all kinds of setups or server hosts.
auto-setup: false

# NMS - Only for 1.19.3
# PACKET - Only up to 1.19.2
mode: NMS

# Readd clickable URLs in messages.
# Could cause incompabilities!
clickable-urls: false

# Do not touch ones below!
first-run: false
ask-bstats: false
setup-mode: false
```

**Comment by BySwiizen** [comment]
> > @BySwiizen @MrCrazyAndy @CloudeLecaw
> > Here's the latest release: https://github.com/KaspianDev/AntiPopup/releases/tag/764c2ad Let me know if it works with no issues and confirm by either commenting or closing the issue.
> 
> I agree with Bywiizen. it works like a charm in lattest paper 1.19.4. i specified nothing... so what do you mean?
> 
> ```
> this is my current config.
> config-version: '28'
> 
> # Should we collect anonymous data about your server?
> # false by default.
> bstats: false
> 
> # Should we remove [Not Secure] from /say?
> # There is a very small chance of catching something
> # that should not be caught. If that happens report the
> # incident to Github issues of AntiPopup.
> filter-not-secure: true
> 
> # Should we prevent messages from being reported?
> # Leave as true unless you have a different plugin stripping those.
> strip-signature: true
> 
> # We dont need that packet if
> # we dont sign messages.
> dont-send-header: true
> 
> # Should setup be ran on first start?
> # Useful for all kinds of setups or server hosts.
> auto-setup: false
> 
> # NMS - Only for 1.19.3
> # PACKET - Only up to 1.19.2
> mode: NMS
> 
> # Readd clickable URLs in messages.
> # Could cause incompabilities!
> clickable-urls: false
> 
> # Do not touch ones below!
> first-run: false
> ask-bstats: false
> setup-mode: false
> ```

"# NMS - Only for 1.19.3 and 1.19.4"

**Comment by KaspianDev** [comment]
comments dont update

**Comment by CloudeLecaw** [comment]
what about the old settings from cofnig 23?

```
# Give it a try if players get kicked
# with message about unsynced message time.
# UNTESTED
prevent-time-sync-kick: false

# Should we prevent messages from being reported?
# Leave as true unless you have a different plugin stripping those.
strip-signature: true
```

can they be removed? i saw these are no part of the default config anymore...

**Comment by KaspianDev** [comment]
> what about the old settings from cofnig 23?
> 
> ```
> # Give it a try if players get kicked
> # with message about unsynced message time.
> # UNTESTED
> prevent-time-sync-kick: false
> 
> # Should we prevent messages from being reported?
> # Leave as true unless you have a different plugin stripping those.
> strip-signature: true
> ```
> 
> can they be removed? i saw these are no part of the default config anymore...

feel free to remove something if you know it isnt there by default anymore. if its needed it will just regenerate.

**Comment by CloudeLecaw** [comment]
> > what about the old settings from cofnig 23?
> > ```
> > # Give it a try if players get kicked
> > # with message about unsynced message time.
> > # UNTESTED
> > prevent-time-sync-kick: false
> > 
> > # Should we prevent messages from being reported?
> > # Leave as true unless you have a different plugin stripping those.
> > strip-signature: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can they be removed? i saw these are no part of the default config anymore...
> 
> feel free to remove something if you know it isnt there by default anymore. if its needed it will just regenerate.

well i readded it from a backup of config 23. currently i see no difference with these settings in it. so i was not sure if its needed anymore or may not..
