### ISSUE TITLE
[BUG] Massive errors on server boot?

### ISSUE THREAD

**Issue by DerpDerpingtonIsHere** [KaspianDev/AntiPopup#43]
### Describe the bug

I am getting a bunch of errors on my server hosted by pebblehost if that matters. This can be seen [Here](https://pastebin.com/93VGGCp8)

Server Jar is: "Purpur" version git-Purpur-1882 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: fcefd04 on HEAD) This is what is provided by pebblehost.

Minecraft version is: 1.19.3.

Anti popup version is: AntiPopup-5.3

### To Reproduce

1. Install jar
2. Run server
3. Errors start

### Expected behavior

Not spam my console with errors.

### Operating System

Linux

### Server Software

Purpur-1882

### Server Version

1.19.3

### Proxy Type

None

### Plugin List

```bash
AntiPopup, ChestSort, CoalConverter, CoreProtect, CraftEnhance, DisablePoppyDrops, Elevators, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, FastSleep, IronOpener, ItemSorter, JumpCrouch, LuckPerms, mcMMO, Minepacks, NoCreeperGriefing, Orebfuscator, PlaceholderAPI, ProtocolLib, ServerSigns, SimpleDropInventory, SimpleTrash, spark, SpecificMobDisable, TreeFeller, Twerking-Crops*, UnstripLog, Vault, YetAnotherHarvest
```

### Server logs

https://pastebin.com/Zi3X3N4H

**Comment by KaspianDev** [comment]
5.4 should fix
https://github.com/KaspianDev/AntiPopup/releases/tag/4444b79

**Comment by DerpDerpingtonIsHere** [comment]
> 5.4 should fix https://github.com/KaspianDev/AntiPopup/releases/tag/4444b79

This is actually my bad. I downloaded the updated  5.4 but forgot to actually put it in my plugins folder... I should have looked again.
