### ISSUE TITLE
ViaVersion/ViaBackwards doesn't work with this plugin installed

### ISSUE THREAD

**Issue by Alcrafter-YT** [KaspianDev/AntiPopup#5]
First: This plugin is wonderful, keep up the good work.

Unfortunately, it seems to be incompatible with ViaVersion/Backwards, as that lower versions can't join the server with this plugin active.

Server: Paper-1.19.1
Client: Any Vanilla client that is lower than 1.19 and supported by VIaVersion/Backwards

How to reproduce: Install the plugin on the server with ViaVersion and ViaBackwards and try to join with, e.g., 1.16.

Console Error: https://mclo.gs/tvAkLBk

**Comment by MWHunter** [comment]
What plugins are you using?  What version of ProtocolLib, if you have it

**Comment by KaspianDev** [comment]
> What plugins are you using? What version of ProtocolLib, if you have it

It can be reproduced without PLib installed, viaversion i reproduced with was https://ci.viaversion.com/job/ViaVersion/631/ this build and https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/279/

**Comment by KaspianDev** [comment]
Resolved in latest version
