### ISSUE TITLE
[Feature Request] Folia Support

### ISSUE THREAD

**Issue by R00tB33rMan** [KaspianDev/AntiPopup#50]
Do you intend on integrating Folia support in the near future or is this out of the picture? FreedomChat as of recently has implemented compatibility; just wanted to see if you are intending to integrate compatibility as well.

**Comment by KaspianDev** [comment]
no idea what folia is, if you with to add support open a pull request

**Comment by R00tB33rMan** [comment]
No worries. This is Folia: https://github.com/PaperMC/Folia

I unfortunately do not have the capabilities. Just wanted to mention it to you, just so you are aware. It's quite a cool upcoming project. Thought it might be of interest, given it's under PaperMC's branch.

**Comment by Aitooor** [comment]
Will this be added?

**Comment by KaspianDev** [comment]
> Will this be added?

If someone wants to pr this change feel free to do so, I will merge it.

**Comment by KaspianDev** [comment]
scheduled for 1.20, note that unless theres some library folia provides i will not add direct support for it in the code itself

**Comment by BySwiizen** [comment]
I just tried the plugin on Folia and indeed it needs an update for it to work.

**Error log: https://pastebin.com/zetntShM**

**Comment by KaspianDev** [comment]
> I just tried the plugin on Folia and indeed it needs an update for it to work.
> 
> **Error log: https://pastebin.com/zetntShM**

yea it wont boot until i clearly mark it as supported

**Comment by KaspianDev** [comment]
Resolved by #56.
