### ISSUE TITLE
[BUG] Invalid chat packets and invalid verification

### ISSUE THREAD

**Issue by jonaas13** [KaspianDev/AntiPopup#51]
### Describe the bug

I recently updated my server network to 1.19.4. Ever since players have reported getting kicked for invalid chat packets. It's quite random and doesn't happen for all messages, not sure what the issue is.

I'm using Purpur 1.19.4 (latest build). Also running Waterfall setup (ViaVersion and AntiPopup-Via is installed), Protocollib is also latest version.

Errors on console: https://pastebin.com/xnpBZ8xH

### To Reproduce

1. Make a 1.19.4 server (purpur/paper).
2. Test Plugin
3. Send chat messages
4. get kicked on occasion

### Expected behavior

Players should not get kicked.

### Operating System

Ubuntu Server

### Server Software

Purpur 1.19.4

### Server Version

1.19

### Proxy Type

Waterfall

### Plugin List

```bash
AntiPopup, LuckPerms, Viaversion, more... (I have over 20 servers all with different plugins)
```

### Server logs

https://pastebin.com/xnpBZ8xH

**Comment by jonaas13** [comment]
```
# NMS - Only for 1.19.3 and 1.19.4.
# PACKET - Only up to 1.19.2.
mode: PACKET
```

Saw this in the config, does switching it to NMS fix it? 
I saw a discord message with similar issues, it ended up kicking all players (for them).

**Comment by KaspianDev** [comment]
> ```
> # NMS - Only for 1.19.3 and 1.19.4.
> # PACKET - Only up to 1.19.2.
> mode: PACKET
> ```
> 
> Saw this in the config, does switching it to NMS fix it? I saw a discord message with similar issues, it ended up kicking all players (for them).

yes you gotta use NMS mode on 1.19.3 +
