### ISSUE TITLE
[Issue] Does not work in 1.20

### ISSUE THREAD

**Issue by kalleswe** [KaspianDev/AntiPopup#54]
### Describe the bug

Please add support for 1.20, since it throws errors when trying to load it there.

### To Reproduce

asdfasdf

### Expected behavior

asdfasdf

### Operating System

asdfasdf

### Server Software

Paper 1.20

### Server Version

1.19

### Proxy Type

Waterfall

### Plugin List

```bash
sdafgsdfg
```

### Server logs

asdfasdf

**Comment by KaspianDev** [comment]
Please use blank template for such issues.

1.20 support progress is being tracked on my [discord](https://discord.gg/eak2zA4s6m)
