### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by blaubeere1** [KaspianDev/AntiPopup#62]
### Describe the bug

Anit chat reporting not working on players that are offline / different server (in a Lobby or another gamemode)

### To Reproduce

1. Go to Report Player
2. Any player that is offline can be reported

### Expected behavior

Blocking Chat Reports for all players (online or offline)
### Operating System

Ubuntu Linux  (Servers running on Pterodactyl)

### Server Software

Paper (Git: 81619a6)

### Server Version

1.20.1

### Proxy Type

Bungeecord

### Plugin List

```bash
AntiPopup, FastAsyncWorldEdit, LPC, LuckPerms, Multiverse-Core, PlaceholderAPI, PlotSquared, ProtocolLib, Skript, *skript-placeholders, SkUniversal, TAB
```

### Server logs

No Errors

**Comment by KaspianDev** [comment]
resolved in dms
