### ISSUE TITLE
[BUG] PlayerJoinEvent packet_handler

### ISSUE THREAD

**Issue by NewPixelDev** [KaspianDev/AntiPopup#63]
### Describe the bug

This error will cause the server to freeze, causing all players to collectively freeze for about a minute.

### To Reproduce

1. Put AntiPopup into Plugin
2. run
3. This problem happens randomly

### Expected behavior

This error will cause the server to freeze, causing all players to collectively freeze for about a minute.

### Operating System

Microsoft Windows Server 2022 Datacenter

### Server Software

 Current: git-Purpur-2035 (MC: 1.20.1)* Previous: git-Purpur-2034 (MC: 1.20.1) * You are running the latest version

### Server Version

1.20.1

### Proxy Type

Waterfall

### Plugin List

```bash
Paper Plugins: (2):
 - BKCommonLib, MarriageMaster
 Bukkit Plugins: (40):
 - AntiPopup, BetterRTP, BlockParticles, ChatGames, Chunky, Citizens, CMI, *CMIEInjector, CMILib, CommandWhitelist
 CustomWings, DecentHolograms, DeluxeMenus, Dualhorse, EnderDragon, EvenMoreFish, ExcellentEnchants, FastAsyncWorldEdit, FastChunkPregenerator, *GambleBarPro
 Iris, LiteSignIn, LPC, LuckPerms, My_Worlds, NBTAPI, NexEngine, PlaceholderAPI, PlayerPoints, ProtocolLib
 QuickShop, RealisticSeasons, Residence, RewardsLite, spark, SternalBoard, TAB, TerraformGenerator, Vault, WorldGuard
```

### Server logs

https://pastebin.com/LCq3vKcX

**Comment by KaspianDev** [comment]
Did you reload your server during the session?

**Comment by NewPixelDev** [comment]
I never "/reload" the server, I usually "/stop" to stop the server

**Comment by KaspianDev** [comment]
I can't really reproduce it, I would need specific reproduction steps.

**Comment by NewPixelDev** [comment]
This problem happens randomly, sorry, I don't know how to trigger this problem in detail.

**Comment by KaspianDev** [comment]
Test with [this](https://github.com/KaspianDev/AntiPopup/actions/runs/5917303556) @NewPixelDev
