### ISSUE TITLE
[ERROR] java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by Nishh** [KaspianDev/AntiPopup#64]
### Describe the bug

Error on console.

Stack trace: https://pastebin.com/E3jj69Kc

### To Reproduce

1. Restart server.
2. Kick all players while restarting

### Operating System

Ubuntu

### Server Software

Paper (550, 1.19.4)

### Server Version

Not Listed

### Proxy Type

Waterfall

### Plugin List

```bash
Addons v1.0
AdvancedBan v2.1.6
AntiAdvertising v2.1.6
AntiPopup v6.2
ArmorEquipEvent v1.7.3
ArmorStandTools v4.4.4
BeautyQuests v0.16_BUILD${build.number}
BetterInvisibility v1.1.0
BKCommonLib v1.19.4-v1
Builders-Utilities v2.1.1-75
BuycraftX v12.0.8
Citizens v2.0.32-SNAPSHOT (build 3169)
Clans v0.4.2
ClansChatAddon v0.0.5
ClansShowAddon v0.0.3
ClientStats v2.12.0
ColoredSigns v3.0
ConsoleSpamFix v1.8.5
CoreProtect v21.3
CrazyAuctions v1.2.16-RELEASE
DiscordSRV v1.26.2
DropsDisplay v0.0.2
DynamicShop v${project.version}
dynmap v3.5-873
EntityDetection v1.1.3 (build #21)
FastAsyncWorldEdit v2.7.1-SNAPSHOT-548;fe33be5
FileGUI vPhase 67
FlySpeed v2.1.0
GadgetsMenu v4.9.5
GPS v2.19.26
GSit v1.4.0
HolographicDisplays v3.0.3
LastLoginAPI v1.7.2
LightCleaner v1.19.3-v1
Liweth v1.0
LiwethLoader v1.0
LuckPerms v5.4.102
MLGDamageIndicators v${project.version}
MobArena v0.104
Multiverse-Core v4.3.1-b861
NPC_Destinations v2.6.16
OpenInv v4.3.1
Parties v2.6.3
Plan v5.5 build 2461
PlugManX v2.3.1
PrivateMessages v3.0-Beta6
ProtocolLib v5.0.0
RegionAPI v1.0.0
Renk v1.0
Sentinel v2.7.3-SNAPSHOT (build 505)
ServerListPlus v3.5.0
ServerTutorialPlus v1.21.3
setMaxSlots v1.1
SimpleHomes v2.0.4
SimpleRename v13.0
SimpleTpa v6.4
SkinsRestorer v14.2.12
SkyParticles v1.0
SmartSignEditor v2.7.7
spark v1.10.34
Spartan vPhase 520
SuperVanish v6.2.17
ThirdChance v2.1
TitleManager v2.3.6
TradeSystem v2.5.0
UltimateStatistics vPhase 135
Vault v1.7.3-b131
ViaBackwards v4.7.0
ViaVersion v4.7.0
VoidGen v2.2.1
VotifierPlus v1.0.4
VotingPlugin v6.7.1
VoxelSniper v8.12.3
WeBrush v1.1.2
WorldBorder v1.9.10 (beta)
WorldEditSelectionVisualizer v2.1.3
WorldGuard v7.0.7+216b061
zChat v0.3.2
```

### Server logs

https://pastebin.com/ikUS3cUA

**Comment by KaspianDev** [comment]
Did you reload your server?

**Comment by Nishh** [comment]
No. I have reload command disabled. Also did NOT use plugman reload.

**Comment by KaspianDev** [comment]
If it happens all the time reinstall the plugin, jar might be corrupted.

**Comment by Nishh** [comment]
This happened only once. I will still reinstall it just in case.

**Comment by Nishh** [comment]
Happened again. Exact same error exact same time.

**Comment by KaspianDev** [comment]
I have no idea, something is broken with your jar.

**Comment by Nishh** [comment]
Checksum file:
58e1a9d3e531ef36dcfd14255ffa336f build/libs/AntiPopup-6.2.jar

/plugins # md5sum AntiPopup-6.2.jar command result:
58e1a9d3e531ef36dcfd14255ffa336f  AntiPopup-6.2.jar

They are identical. I will try adding softdepend:[AntiPopup] to the plugin that kicks players.

**Comment by Nishh** [comment]
Even though kicking is happening after these messages:
[06:49:02] [Server thread/INFO]: [AntiPopup] Disabling AntiPopup v6.2
[06:49:02] [Server thread/INFO]: [AntiPopup] Disabled PacketEvents.
same error still thrown.

**Comment by KaspianDev** [comment]
No idea what's going on there, try removing plugins one by one
