### ISSUE TITLE
[README] 1.20.2 Update

### ISSUE THREAD

**Issue by BySwiizen** [KaspianDev/AntiPopup#65]
### Describe the bug

Hi! When I try to join the server, I get kicked out after a few seconds and I get an error message.

I think it's due to 1.20.2 but I prefer to inform you anyway!

### To Reproduce

1. Start the server
2. Join the server

### Expected behavior

Being able to join the server without being kicked.

### Operating System

Windows

### Server Software

PaperSpigot 1.20.2 (197)

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
AntiPopup, ProtocolLib
```

### Server logs

https://pastebin.com/m6whdMTK

**Comment by KaspianDev** [comment]
Yeah let's turn this into 1.20.2 issue.
Expect it to be delayed by a week or two tho.

**Comment by envizar** [comment]
+1 to "please update it asap"

**Comment by KaspianDev** [comment]
AntiPopup depends on packetevents so I have to wait for it to update first.

**Comment by envizar** [comment]
> AntiPopup depends on packetevents so I have to wait for it to update first.

https://github.com/retrooper/packetevents/actions

**Comment by KaspianDev** [comment]
> > AntiPopup depends on packetevents so I have to wait for it to update first.
> 
> https://github.com/retrooper/packetevents/actions

We're using v2

**Comment by CloudeLecaw** [comment]
I hope Version 6.3 will also include the option to block reporting for skin and name.

Currently:
Tested on 1.20.1 with 1.20.2 client (viaversion)  the players have the option to report names and skin while chat is blocked fine by Antipopup.

**Comment by BySwiizen** [comment]
> > > AntiPopup depends on packetevents so I have to wait for it to update first.
> > 
> > 
> > https://github.com/retrooper/packetevents/actions
> 
> We're using v2

There was an update for 1.20.2. _https://github.com/retrooper/packetevents/commit/4e151f8dfb482d81ead9c58793b380596c29b3f1_

**Comment by KaspianDev** [comment]
Please test this https://github.com/KaspianDev/AntiPopup/actions/runs/6443268007

**Comment by BySwiizen** [comment]
> Please test this https://github.com/KaspianDev/AntiPopup/actions/runs/6443268007

This seems OK to me!

**Comment by CloudeLecaw** [comment]
aww dobwe need to gradle itself now? :3

**Comment by KaspianDev** [comment]
> aww dobwe need to gradle itself now? :3

wdym?

**Comment by CloudeLecaw** [comment]
hmm might be because for the user its more simple to have a jar ready to download?

**Comment by KaspianDev** [comment]
> hmm might be because for the user its more simple to have a jar ready to download?
> 
> gradle is nothing a normal user should need to do :3

The action has generated an artifact, scroll down on that page and click the button saying `artifact`

**Comment by SebiTimeWaster** [comment]
is there a release planned?

**Comment by CloudeLecaw** [comment]
> is there a release planned?

currently not but may   Version 7 will come soon.

You can get the current developstate of Version 7 here: [Java CI with Gradle · KaspianDev/AntiPopup@b022929 · GitHub](https://github.com/KaspianDev/AntiPopup/actions/runs/6443268007)
Scroll down to the articfacts.zip and download it. Inside the artifact.zip you find the current developstate version 7 jarfile that is ready for 1.20.2
Dont forget to update aggain when its relased on Spigot ;)

![image](https://github.com/KaspianDev/AntiPopup/assets/12080017/92d2b788-458c-47ee-8430-40ae1ce6a2c2)

**Comment by CloudeLecaw** [comment]
ticjet can be closed. the version 7 for 1.20.2 was released ;)

**Comment by SebiTimeWaster** [comment]
awesome! :)

**Comment by KaspianDev** [comment]
thank you all for your time
