### ISSUE TITLE
[BUG] 1.20.2 join message

### ISSUE THREAD

**Issue by SwartZCoding** [KaspianDev/AntiPopup#68]
### Describe the bug

When i join my server using antipopup V7 i have message like this on my join message : 

<img width="415" alt="image" src="https://github.com/KaspianDev/AntiPopup/assets/39431572/56716aa3-f4d4-4e3f-af38-77e7f387220b">

### To Reproduce

1. Download v7
2. Make a plugin which send message on join.
3. Try yourself

### Operating System

Arch Linux

### Server Software

git-Purpur-2030 (MC: 1.20.1)

### Server Version

1.20.1

### Proxy Type

Other

### Plugin List

```bash
Can provide in DM
```

### Server logs

No

**Comment by KaspianDev** [comment]
That is not a message antipopup would send.
I need your server plugin list and logs to help, dm me those on discord if you want privacy.

**Comment by KaspianDev** [comment]
no response
