### ISSUE TITLE
[BUG] server.properties relocation sends exception on startup

### ISSUE THREAD

**Issue by BenceX100** [KaspianDev/AntiPopup#69]
### Describe the bug

So it's possible to relocate the server.properties and antipopup throws an exception because it can't find it

### To Reproduce

1. Use the in `--config startup` flag (example: `--config config/server.properties`) to relocate the server.properties.
2. Delete the original server.properties.
3. Start the server and look in the console

### Expected behavior

The plugin should read the startup flags and find the file.

### Operating System

Ubuntu

### Server Software

Folia-17

### Server Version

1.20.1

### Proxy Type

None

### Plugin List

```bash
AntiPopup
```

### Server logs

https://pastes.dev/EYPgrRxHF8

**Comment by KaspianDev** [comment]
For now you can symlink, I'll get back to you later

**Comment by KaspianDev** [comment]
Added to [antipopup pro](https://polymart.org/resource/antipopup-pro.4921) normal release tomorrow
