### ISSUE TITLE
[README] 1.20.4 Update

### ISSUE THREAD

**Issue by BySwiizen** [KaspianDev/AntiPopup#74]
### Describe the bug

Hi! When I start the server, I get an error message in the console and the plugin disables it.

I think it's due to 1.20.4 but I prefer to inform you anyway!

### To Reproduce

1. Start the server
2. See error message in console

### Expected behavior

No longer have an error message and the plugin works.

### Operating System

Windows

### Server Software

PaperSpigot 1.20.4 (319)

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
AntiPopup, ProtocolLib
```

### Server logs

https://pastebin.com/msxMQ05L

**Comment by KaspianDev** [comment]
https://github.com/retrooper/packetevents/pull/623

**Comment by BySwiizen** [comment]
> [retrooper/packetevents#623](https://github.com/retrooper/packetevents/pull/623)

https://github.com/retrooper/packetevents/commit/1e919053c64c529084ebe8277660f802f949c3a5

**Comment by BySwiizen** [comment]
The plugin has been updated.
