### ISSUE TITLE
Typo on spigot website

### ISSUE THREAD

**Issue by CoolManTheCool** [KaspianDev/AntiPopup#77]
[AntiPopup](https://www.spigotmc.org/resources/%E2%9C%A8-antipopup-no-chat-reports-and-popup-%E2%9C%A8.103782/) there is a typo on the website under Faq
"A: Yes, you server will have a verified badge."
You should be your.

**Comment by PukPukov** [comment]
>in progress

I hope one day this monumental task will be finished.
