### ISSUE TITLE
[BUG] Unable to grab ViaVersion client version for spam bug

### ISSUE THREAD

**Issue by Yomamaeatstoes** [KaspianDev/AntiPopup#78]
### Describe the bug

I keep on getting a message saying unable to grab ViaVersion client version 

### To Reproduce

To be honest I don't know how to produce this, or if others are experiencing it.

### Expected behavior

For it to stop checking if it can't get the version.

### Operating System

Ubuntu

### Server Software

Folia

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
AntiPopup, AutoPay, BetterBoard, BetterEconomy, BetterRTP, BetterRTPAddons, BisectHosting-Folia, BloCommands, ChatFilter, Chunky, ClansLite, DeluxeMenus, DisableBreeding, DiscordSRV, ElytraSpeed, EpicHomes, floodgate, GlobalTrackedMaps, GrimAC, IllegalStack, ImageFrame, LuckPerms, mcMMO, MutePlus, PL-Hide, PlaceholderAPI, PlayerBountiesPlus, PlayerKits2, PlugManX, ProtocolLib
 RedLimiterReloaded, ScoreboardChatShop, SilkySpawnersLITE, spark, StackMob, StormerAntiSpamReloaded, StormerWarpsReloaded, SuperVanish, TAB, TerragenBiomesMockRegistry
Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard, YATPA, ZNPCsPlus
```

### Server logs

https://mclo.gs/cxgByou

**Comment by KaspianDev** [comment]
https://github.com/retrooper/packetevents/issues/680

**Comment by Yomamaeatstoes** [comment]
> [retrooper/packetevents#680](https://github.com/retrooper/packetevents/issues/680)

Thank you!

**Comment by KaspianDev** [comment]
https://github.com/retrooper/packetevents/issues/680#issuecomment-1963095180

For those who still have the problem
