### ISSUE TITLE
[BUG] Antipopup 7.3 not work on Paper 1.20.4 build 464

### ISSUE THREAD

**Issue by Reserf0rd** [KaspianDev/AntiPopup#84]
### Describe the bug

Plugin dont hide pop up message. Im use version 7.3. Update my test server from Paper 1.19.4 build 550 (plugin work) to Paper 1.20.4 build 464 and plugin dont work. Nothing else changed - old datapack, old plugin without update. Trying delete and download, plugin started but dont hide pop up

### To Reproduce

1. Install new sever with Paper 1.20.4 build 464
2. Download and install AntiPopup 7.3
3. Type /antipopup setup in console, stop and start server

### Expected behavior

This version (7.3) works fine in Paper 1.19.4, but in 1.20.4 something broken

### Operating System

Ubuntu 18

### Server Software

Paper 1.20.4 build 464

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
[11:20:02 INFO]: Server Plugins (7):
[11:20:02 INFO]: Bukkit Plugins:
[11:20:02 INFO]:  - AntiPopup, Authy, Chunky, ComfyWhitelist, LightPerms, ServerBackup, ServerHider
```

### Server logs

Logs clear, without error

**Comment by Reserf0rd** [comment]
Find interesting moment: plugin not work on launcher Tlauncher Legacy (aka TL Launcher) and llaun.ch. On Tlauncher (tlauncher.org) it works fine. Same version (Optifine 1.20.4, vanilla 1.20.4 client), same user, same all but different launcher.

3 players on Tlauncher don't see pop up, other 6 players with another launcher see it

**Comment by SonnenPingu** [comment]
For me anti popup on 1.20.4 work fine only on the new version of paper 1.20.5 does not work #85

**Comment by KaspianDev** [comment]
> For me anti popup on 1.20.4 work fine only on the new version of paper 1.20.5 does not work #85

We're waiting for [retrooper/packetevents#](https://github.com/retrooper/packetevents/pull/658)

**Comment by BySwiizen** [comment]
> > For me anti popup on 1.20.4 work fine only on the new version of paper 1.20.5 does not work #85
> 
> We're waiting for [retrooper/packetevents#658](https://github.com/retrooper/packetevents/pull/658)

He was merged.

**Comment by KaspianDev** [comment]
> > > For me anti popup on 1.20.4 work fine only on the new version of paper 1.20.5 does not work #85
> > 
> > 
> > We're waiting for [retrooper/packetevents#658](https://github.com/retrooper/packetevents/pull/658)
> 
> He was merged.

yup i'm aware, no release yet however

**Comment by LEMIBANDDEXARI** [comment]
https://github.com/retrooper/packetevents/releases/tag/v2.3.0
