### ISSUE TITLE
[QUESTION] Java 17 Support

### ISSUE THREAD

**Issue by AlexDerProGamer** [KaspianDev/AntiPopup#87]
Could you readd support for Java 17 because most servers still use Java 17 (including mine) and 1.20.5 client support is needed very much.

If that's too much work I can totally understand, but it would be still very appreciated!

**Comment by KaspianDev** [comment]
Is there any reason you can't update to java 21?

**Comment by AlexDerProGamer** [comment]
It would take a while to recode all the things because basically every server and program of mine is running on Java 17.

And I think 1.21 will need Java 21 anyways so maybe wait with the Java update for you plugin until 1.21? So when other people want to use it for eg 1.20.5 they will be forced to use Java 21 even though everything else can run with Java 17. I hope that's understandable...

**Comment by KaspianDev** [comment]
> It would take a while to recode all the things because basically every server and program of mine is running on Java 17.
> 
> And I think 1.21 will need Java 21 anyways so maybe wait with the Java update for you plugin until 1.21? So when other people want to use it for eg 1.20.5 they will be forced to use Java 21 even though everything else can run with Java 17. I hope that's understandable...

Updating to java 21 shouldn't break anything

**Comment by AlexDerProGamer** [comment]
Okay, I can try...
