### ISSUE TITLE
[BUG] custom payload is too large in minecraft version 1.20.5

### ISSUE THREAD

**Issue by AlexDerProGamer** [KaspianDev/AntiPopup#89]
### Describe the bug

<img width="906" alt="image" src="https://github.com/KaspianDev/AntiPopup/assets/111710468/738e503f-ddee-4d2b-9d11-d68ce3728a2e">

when joining with a 1.20.5 client i get disconnected immediately (clients from 1.20 to 1.20.4 can connect normally)

### To Reproduce

1. setup the server with the infos given
2. connect to the server with 1.20.5
3. see the error message

### Expected behavior

join the server without a error message

### Operating System

client: windows, server: linux

### Server Software

paper 1.20.4 #496

### Server Version

Not Listed

### Proxy Type

Velocity

### Plugin List

```bash
antipopup 8.1,
viaversion 4.10.2,
viabackwards 4.10.2
```

### Server logs

no logs, only "Player lost connection: Disconnected"

**Comment by KaspianDev** [comment]
Please confirm without antipopup.
(is it installed on the proxy? if so remove it from there and retry)

**Comment by AlexDerProGamer** [comment]
okay, apparently antipopup was installed on the proxy AND the backend,
dont really know how that happenend

thanks for your help!
