### ISSUE TITLE
Cancelling AsyncPlayerChatEvent with AntiPopup causes kicks with ViaVersion

### ISSUE THREAD

**Issue by SnickoDeadMC** [KaspianDev/AntiPopup#9]
Cancelling the AsyncPlayerChatEvent event with AntiPopup can cause players to be kicked with 'Chat message validation failed'.
This happens when a player on a version <1.19.1 sends a message, and it will kick all players that are on 1.19.1 and 1.19.2.

**To reproduce:**
On a fresh server, install AntiPopup, ViaVersion and ViaBackwards.

Use a plugin with the event registered:

`	@EventHandler
	public void onTalkEvent(AsyncPlayerChatEvent event) {
                event.setCancelled(true);
        }`

Login with player A on >=1.19.1
Login with player B on <1.19.1

Notice the message is cancelled as expected, however player A (on >=1.19.1) is kicked from the server with 'Chat message validation failed' kick message, and player B is still on the server.

Now uninstall AntiPopup and reload. Do the above steps and notice the messages being cancelled as intended (and no players are kicked).
Note: I think there is something cached with the player but the first time chatting after uninstalling and reloading, the player is kicked like before. However it doesn't happen again once after.

**Comment by KaspianDev** [comment]
Never ever reload the server. Please reproduce after restart.

**Comment by KaspianDev** [comment]
Can't reproduce with your code, reopen if you still have the issue after steps i told you.
