### ISSUE TITLE
would be nice to have a Version for 1.21.

### ISSUE THREAD

**Issue by CloudeLecaw** [KaspianDev/AntiPopup#92]
### Describe the bug

currently the plugin is not running for the new 1.21 server version :3

### To Reproduce

1. get latest spigot version 1.21
2. get Antipopup 8.1
3. start server

### Operating System

a linux

### Server Software

spigot 1.21

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
Antipopup, Procollib, Pex
```

### Server logs

https://pastebin.com/qgwhcsBg

**Comment by blackenergypt** [comment]
I also have the same problem

**Comment by CloudeLecaw** [comment]
> I also have the same problem

You see the state is in progress

 That means he is working on it :)

**Comment by BySwiizen** [comment]
https://github.com/retrooper/packetevents/pull/732

**Comment by CloudeLecaw** [comment]
> [retrooper/packetevents#732](https://github.com/retrooper/packetevents/pull/732)

i see. its merged..so where to get the jar file? :3

**Comment by CloudeLecaw** [comment]
So does Antipop now require the plugin PacketEvents? :3

**Comment by KaspianDev** [comment]
Always did but is a shaded dependency

**Comment by CloudeLecaw** [comment]
interesting. we never used the plugin on our server..mean i never downloaded it.. so its internal inside Antipopup? :3

**Comment by KaspianDev** [comment]
Yes shaded means antipopup provides it inside of itself.

**Comment by BySwiizen** [comment]
https://github.com/retrooper/packetevents/releases/tag/v2.4.0

**Comment by KaspianDev** [comment]
#94
