### ISSUE TITLE
PacketEvents 2.0 failed to inject.

### ISSUE THREAD

**Issue by BAD7777** [KaspianDev/AntiPopup#93]
Hi. Some players are unable to connect due to the error: "lost connection: PacketEvents 2.0 failed to inject."
It seems the problem is related to ViaVersion. The new version is 5.0.1, and you still have support for 4.10.1. There have been major changes in this version of the plugin.

Checking version, please wait...
Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)
You are running the latest version
Previous: 1.20.6-2232-f1c87e4 (MC: 1.20.6)

**Comment by KaspianDev** [comment]
#94

**Comment by KaspianDev** [comment]
Fill in the bug form
