### ISSUE TITLE
[BUG] 'Narrator: Narrates Chat' Accessibility Setting Not Working

### ISSUE THREAD

**Issue by Onys-0** [KaspianDev/AntiPopup#98]
### Describe the bug

When the Minecraft chat narrator is enabled, it doesn't narrate chat messages correctly with this plugin installed. This is likely because the messages are recognized as system messages instead of chat, but I wanted to bring this to your attention even though I know there's likely nothing that can be done.

### To Reproduce

1. Navigate to `options` -> `accessibility settings`.
2. Set the option `Narrator` to `Narrates Chat`. 
3. Send a chat message and observe that it isn't being narrated.

### Expected behavior

I expected the narrator to say "0nys says test" immediately after sending the message "test" to the server.

### Operating System

Windows 11 Home 23H2

### Server Software

Paper 1.21 (103)

### Server Version

1.2

### Proxy Type

None

### Plugin List

```bash
AntiPopup
```

### Server logs

https://pastebin.com/2v7L1PXi

**Comment by KaspianDev** [comment]
If Minecraft only translates signed messages there's nothing I can do.

**Comment by Onys-0** [comment]
I hadn't thought of that yet, thanks! I'll try coding a mod for it
